version: "3.6"

services:
  web-service:
    build: "."
    command: "web-service"
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: "distributedLogs"
      POSTGRES_USER: "ravjot"
      POSTGRES_PASSWORD: "ravjot"
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "distributedLogs"
      POSTGRES_USER: "ravjot"
      POSTGRES_PASSWORD: "ravjot"
    ports:
      - "5432:5432"
